STATES_SIMPLIFIED = {
    'ANDAMAN AND NICOBAR ISLANDS': '35',
    'ANDHRA PRADESH': '28',
    'ARUNACHAL PRADESH': '12',
    'ASSAM': '18',
    'BIHAR': '10',
    'CHHATTISGARH': '22',
    'GOA': '30',
    'GUJARAT': '24',
    'HARYANA': '6',
    'HIMACHAL PRADESH': '2',
    'JHARKHAND': '20',
    'KARNATAKA': '29',
    'KERALA': '32',
    'MADHYA PRADESH': '23',
    'MAHARASHTRA': '27',
    'MANIPUR': '14',
    'ODISHA': '21',
    'PUNJAB': '3',
    'RAJASTHAN': '8',
    'SIKKIM': '11',
    'TAMIL NADU': '33',
    'TELANGANA': '36',
    'TRIPURA': '16',
    'UTTARAKHAND': '5',
    'UTTAR PRADESH': '9',
    'WEST BENGAL': '19'
}
